export { default as MainSlider } from "./MainSlider/MainSlider";
export { default as FiltersControl } from "./FiltersControl/FiltersControl";
export { default as Products } from "./Products/Products";
export { default as AboutUs } from "./AboutUs/AboutUs";
export { default as Benefits } from "./Benefits/Benefits";
export { default as Reservation } from "./Reservation/Reservation";
export { default as Customers } from "./Customers/Customers";
export { default as Feedback } from "./Feedback/Feedback";
export { default as Sidebar } from "./Sidebar/Sidebar";
